### ISSUE TITLE
Calculate all password hash

### ISSUE THREAD

**Issue by gravit0** [microwin7/Gravit-Request#1]
https://github.com/microwin7/Gravit-Request/blob/209ee75e4cc6e4212d0cb5c3ef843167894fb81b/request.php#L4
Подсчет всех возможных хешей пароля в начале скрипта ведет к потере производительности
Подсчет выполняется до каких либо проверок и ограничений, что делает скрипт идеальной целью для DDoS

**Comment by microwin7** [comment]
Это будет перенесено, иначе соль не заработает

**Comment by microwin7** [comment]
Перенесено непосредственно в место проверки паролей
