### ISSUE TITLE
Проблемы с безопасностью logs

### ISSUE THREAD

**Issue by gravit0** [microwin7/Gravit-Request#2]
https://github.com/microwin7/Gravit-Request/blob/209ee75e4cc6e4212d0cb5c3ef843167894fb81b/request.php#L82
Логи может прочитать кто угодно, включая логины и хеши(в том числе слабые) переданных паролей. Даже взлом БД не нужен

**Comment by microwin7** [comment]
Не предназначено для релиза, выложил случайно при второй правке

**Comment by microwin7** [comment]
Логи удалены. Сделана дебаг с возможностью включить, для Базы Данных
