### ISSUE TITLE
Чтение файлов

### ISSUE THREAD

**Issue by gravit0** [microwin7/Gravit-Request#3]
https://github.com/microwin7/Gravit-Request/blob/209ee75e4cc6e4212d0cb5c3ef843167894fb81b/request.php#L112
Позволяет читать любые .png на сервере(указав ../../.. в login)

**Comment by microwin7** [comment]
Логин перед обращением проходит проверку через regexp

**Comment by microwin7** [comment]
Настройка только в скрипте пути, нет возможности выйти из папки, проверка логина по Regexp
